### ISSUE TITLE
License

### ISSUE THREAD

**Issue by momer** [dekadentno/vue-unit-testing-cheat-sheet#1]
@dekadentno have you considered adding a license to allow for usage & contributions? Consider https://choosealicense.com/licenses/apache-2.0/

**Comment by dekadentno** [comment]
Thanks for your suggestion. I've added the license, PRs, suggestions, contributions are always welcome. https://github.com/dekadentno/vue-unit-testing-cheat-sheet/commit/cedc60320da284f1cd21f30b027cf443f77af0f0

**Comment by momer** [comment]
Perfect, thank you
